version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types: 
          - "minor"
      patch:
        update-types: 
          - "patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
